'Egor: homework_23 done'
eugene-okulik/Egor pull request #41
Opened 2024-07-29 18:45 UTC by KovalenkoEgor

2024-07-30 12:04 UTC, eugene-okulik requested changes
Автотесты - это тоже программа. А все программы нужно тестировать и проверять, что они выполняют то, что должны. И вот, в одном пункте у тебя программа не сделала то, что должна.

2024-07-30 12:04 UTC, eugene-okulik commented on homework/Egor_Kovalenko/lesson_23/file_1.py
> +    subjects_element.send_keys('Scifi', '2024')
После того как ты уходишь от этого поля, поле остается незаполненным. Нужно понять как работает это поле, а потом проделать эти же действия автоматизацией.

2024-07-30 13:40 UTC, KovalenkoEgor commented on homework/Egor_Kovalenko/lesson_23/file_1.py
> +    subjects_element.send_keys('Scifi', '2024')
Т. Е мне нужно переписать каждый шаг работы в отдельный тест? 
Плюс добавить ввод в шаг выше?)

2024-07-31 07:50 UTC, eugene-okulik commented on homework/Egor_Kovalenko/lesson_23/file_1.py
> +    subjects_element.send_keys('Scifi', '2024')
Нет, конечно. ПРосто сделать так, чтобы программа делала всё, что должна. Про тестирование - я имел ввиду, что когда ты пишешь программу (а автотесты это тоже программы) после того, как дописал проверь, что она делает всё, что нужно.

2024-07-31 07:53 UTC, eugene-okulik approved these changes

2024-07-31 07:53 UTC, merged

2024-07-31 10:01 UTC, KovalenkoEgor commented on homework/Egor_Kovalenko/lesson_23/file_1.py
> +    subjects_element.send_keys('Scifi', '2024')
Ок, я понял)