file from lesson_4
eugene-okulik/Egor pull request #5
Opened 2024-01-09 11:10 UTC by KovalenkoEgor

2024-01-10 07:43 UTC, eugene-okulik requested changes

2024-01-10 07:43 UTC, eugene-okulik commented on homework/Egor_Kovalenko/lesson_4/File1.py
> +my_dict['dict'] = {'i am a tuple': 'i am not a value'}
Этой строкой ты не добавил ключ в то, что находится под ключом dict, а заменил то, что там находилось на `{'i am a tuple': 'i am not a value'}`
И в задании было

> добавьте элемент с ключом ('i am a tuple',) и любым значением

А ты сделал так, кк если бы там было:

> добавьте элемент с ключом 'i am a tuple' и любым значением

2024-01-10 19:17 UTC, eugene-okulik requested changes

2024-01-10 19:17 UTC, eugene-okulik commented on homework/Egor_Kovalenko/lesson_4/File1.py
> +my_dict['i am a tuple'] = 'i am not a value'
Одну проблему починил, но ты всё ещё добавил элемент с ключом 'i am a tuple' вместо ('i am a tuple',) - как было в задании.

2024-01-11 19:10 UTC, KovalenkoEgor commented on homework/Egor_Kovalenko/lesson_4/File1.py
> +my_dict['i am a tuple'] = 'i am not a value'
А почему при добавление элемента ('i am a tuple',) без запятой,  добавляется новый элемент с ключом без скобок, а с запятой со скобками. Что-то я этот момент упустил из урока !!?)

2024-01-12 08:15 UTC, eugene-okulik approved these changes

2024-01-12 08:15 UTC, eugene-okulik commented on homework/Egor_Kovalenko/lesson_4/File1.py
> +my_dict[('i am a tuple',)] = 'i am not a value'
👍

2024-01-12 08:16 UTC, merged